name: lint
on: [pull_request, push, workflow_dispatch]
concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
jobs:
  lint:
    env:
      FORCE_COLOR: 1
      PREK_COLOR: always
      UV_FROZEN: 1
      UV_NO_SYNC: 1
      UV_PYTHON_PREFERENCE: only-managed
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Install Python dependencies
        run: uv sync
      - name: Identify Python version
        id: identify-python
        run: echo "python-version=$(uv run python -V | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
      - name: Cache prek hooks
        id: cache-prek-hooks
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.cache/prek
          key: prek|${{ steps.identify-python.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            prek|${{ steps.identify-python.outputs.python-version }}|
            prek|
      - name: Prune prek hooks
        if: steps.cache-prek-hooks.outputs.cache-hit != 'true'
        run: uv run prek gc
      - name: Run prek
        run: uv run prek run --all-files --show-diff-on-failure
